//! Common software-refinement contracts and proof helpers.
//!
//! Policy-specific projections and transition proofs live in [`budget`] and
//! [`hyperenclave`]. This module retains the policy-neutral region rendering,
//! memory-set projections, and refinement interface shared by those policies.
use vstd::prelude::*;

pub mod budget;
pub mod hyperenclave;

pub use budget::*;

verus! {

use crate::address::addr::SpecVAddr;
use crate::address::frame::SpecFrame;
use crate::address::region::*;
use crate::constants::*;
use crate::hv_mem::spec::budget::*;
use crate::hv_mem::spec::GhostZone;
use crate::memory_set::SpecMemorySet;
use crate::model::convert::*;
use crate::model::software::*;
use crate::model::types::{GuestPage, PhysPage, S2Entry, VmId, VmPageKey};

// ---------------------------------------------------------------------------
// General software-refinement contract
// ---------------------------------------------------------------------------
/// Standard forward-simulation obligations for an arbitrary concrete memory
/// policy. The SW+HW-to-Machine layer consumes only the resulting
/// [`SoftwareView`] trace and never depends on this trait or on `Self`.
pub trait SoftwareRefinement: Sized {
    /// Concrete transition label generated by the policy state machine.
    type Step;

    /// Policy-neutral observation of the concrete policy state.
    spec fn view(&self) -> SoftwareView;

    /// Concrete policy invariant established by its local TSM obligations.
    spec fn invariants(&self) -> bool;

    /// One labeled concrete policy transition.
    spec fn next(pre: Self, post: Self, step: Self::Step) -> bool;

    /// Every invariant concrete state has a well-formed policy-neutral view.
    proof fn invariants_imply_view_wf(&self)
        requires
            #[trigger] self.invariants(),
        ensures
            self.view().wf(),
    ;

    /// A concrete policy step preserves the concrete invariant and simulates a
    /// finite sequence of policy-neutral software operations.
    proof fn step_refines(pre: Self, post: Self, step: Self::Step) -> (ops: Seq<SoftwareOp>)
        requires
            pre.invariants(),
            Self::next(pre, post, step),
        ensures
            post.invariants(),
            run_software_ops(pre.view(), post.view(), ops),
    ;
}

/// Lift one software edge to a singleton execution.
pub proof fn lemma_run_software_ops_single(start: SoftwareView, end: SoftwareView, op: SoftwareOp)
    requires
        SoftwareView::step(start, end, op),
    ensures
        run_software_ops(start, end, seq![op]),
{
    assert(exists|next: SoftwareView|
        SoftwareView::step(start, next, seq![op][0]) && SoftwareView::run_ops(
            next,
            end,
            seq![op].skip(1),
        )) by {
        let next = end;
    }
}

/// Concatenate two adjacent software executions.
pub proof fn lemma_run_software_ops_concat(
    start: SoftwareView,
    middle: SoftwareView,
    end: SoftwareView,
    first: Seq<SoftwareOp>,
    second: Seq<SoftwareOp>,
)
    requires
        run_software_ops(start, middle, first),
        run_software_ops(middle, end, second),
    ensures
        run_software_ops(start, end, first + second),
    decreases first.len(),
{
    if first.len() != 0 {
        let next = choose|next: SoftwareView|
            SoftwareView::step(start, next, first[0]) && SoftwareView::run_ops(
                next,
                middle,
                first.skip(1),
            );
        lemma_run_software_ops_concat(next, middle, end, first.skip(1), second);
        assert((first + second)[0] == first[0]);
        assert((first + second).skip(1) == first.skip(1) + second);
        assert(exists|next: SoftwareView|
            SoftwareView::step(start, next, (first + second)[0]) && SoftwareView::run_ops(
                next,
                end,
                (first + second).skip(1),
            ));
    }
}

// ---------------------------------------------------------------------------
// Concrete-region geometry and its abstract rendering
// ---------------------------------------------------------------------------
/// Guest page occupied by page index `i` of `region`.
pub open spec fn region_guest_page(region: MemoryRegion, i: nat) -> GuestPage {
    gpa_of_vaddr(region.spec_page_vaddr(i))
}

/// `region` contains physical page `page`.
pub open spec fn region_owns_page(region: MemoryRegion, page: PhysPage) -> bool {
    region_phys_pages(region).contains(page)
}

/// `region` contains guest page `gpa`.
pub open spec fn region_owns_gpa(region: MemoryRegion, gpa: GuestPage) -> bool {
    exists|i: nat| 0 <= i < region.pages && #[trigger] region_guest_page(region, i) == gpa
}

/// Physical pages of one concrete region.
pub open spec fn region_pages(region: MemoryRegion) -> Set<PhysPage> {
    region_phys_pages(region)
}

/// Abstract stage-2 entries induced by one concrete region.
pub open spec fn region_s2_entries(zid: nat, region: MemoryRegion) -> Map<VmPageKey, S2Entry> {
    Map::new(
        |key: VmPageKey| key.vm == VmId(zid) && region_owns_gpa(region, key.gpa),
        |key: VmPageKey|
            {
                let i = choose|i: nat|
                    0 <= i < region.pages && region_guest_page(region, i) == key.gpa;
                S2Entry {
                    page: region_phys_page(region, i),
                    access: attr_to_perms(region.attr),
                    generation: 0,
                }
            },
    )
}

/// Render a concrete region as the policy-neutral region used by SoftwareView.
pub open spec fn region_to_abstract(zid: nat, region: MemoryRegion) -> Region {
    Region {
        vm: VmId(zid),
        gpa_base: region.vstart@.0 / SPEC_PAGE_SIZE,
        phys_base: region.pstart@.0 / SPEC_PAGE_SIZE,
        count: region.pages as nat,
        access: attr_to_perms(region.attr),
    }
}

/// Relates concrete frame arithmetic to the physical-page index of a valid region.
pub proof fn lemma_region_phys_page_linear(region: MemoryRegion, i: nat)
    requires
        region.spec_valid(),
        0 <= i < region.pages,
    ensures
        region.pstart@.0 == (region.pstart@.0 / SPEC_PAGE_SIZE) * SPEC_PAGE_SIZE,
        region_phys_page(region, i).0 == region.pstart@.0 / SPEC_PAGE_SIZE + i,
        frame_phys_page(region.spec_frame(i)) == region_phys_page(region, i),
{
}

/// Expresses a valid region's guest page at index `i` as linear page arithmetic.
pub proof fn lemma_region_guest_page_linear(region: MemoryRegion, i: nat)
    requires
        region.spec_valid(),
        0 <= i < region.pages,
    ensures
        region.vstart@.0 == (region.vstart@.0 / SPEC_PAGE_SIZE) * SPEC_PAGE_SIZE,
        region_guest_page(region, i).0 == region.vstart@.0 / SPEC_PAGE_SIZE + i,
{
}

/// Converts a region guest page back to the concrete virtual address at the same index.
pub proof fn lemma_gpa_vaddr_roundtrip(region: MemoryRegion, i: nat)
    requires
        region.spec_valid(),
        0 <= i < region.pages,
    ensures
        vaddr_of_gpa(region_guest_page(region, i)) == region.spec_page_vaddr(i),
{
}

/// Characterizes membership in a concrete region's mappings by its guest-page range.
pub proof fn lemma_region_gpa_mapped_iff(region: MemoryRegion, gpa: GuestPage)
    requires
        region.spec_valid(),
    ensures
        region.spec_mappings().contains_key(vaddr_of_gpa(gpa)) <==> region_owns_gpa(region, gpa),
{
    if region_owns_gpa(region, gpa) {
        let i = choose|i: nat| 0 <= i < region.pages && region_guest_page(region, i) == gpa;
        lemma_gpa_vaddr_roundtrip(region, i);
        region.lemma_mappings_contains_pair(i);
    }
    if region.spec_mappings().contains_key(vaddr_of_gpa(gpa)) {
        region.lemma_mappings_sound(vaddr_of_gpa(gpa));
        let i = choose|i: nat|
            0 <= i < region.pages && vaddr_of_gpa(gpa) == region.spec_page_vaddr(i)
                && region.spec_mappings()[vaddr_of_gpa(gpa)] == region.spec_frame(i);
        lemma_gpa_vaddr_roundtrip(region, i);
        lemma_vaddr_of_gpa_injective(region_guest_page(region, i), gpa);
    }
}

/// Shows the abstract entry for a region agrees with its concrete memory-set mapping.
pub proof fn lemma_region_s2_value(zid: nat, region: MemoryRegion, key: VmPageKey)
    requires
        region.spec_valid(),
        key.vm == VmId(zid),
        region_owns_gpa(region, key.gpa),
    ensures
        region_s2_entries(zid, region).contains_key(key),
        region_s2_entries(zid, region)[key] == frame_to_s2(
            region.spec_mappings()[vaddr_of_gpa(key.gpa)],
        ),
{
    let i = choose|i: nat| 0 <= i < region.pages && region_guest_page(region, i) == key.gpa;
    lemma_gpa_vaddr_roundtrip(region, i);
    region.lemma_mappings_contains_pair(i);
}

/// Produces a guest page shared by two virtually overlapping valid regions.
pub proof fn lemma_vmem_overlap_implies_shared_gpa(first: MemoryRegion, second: MemoryRegion)
    requires
        first.spec_valid(),
        second.spec_valid(),
        first.spec_overlaps_vmem(second),
    ensures
        exists|gpa: GuestPage| region_owns_gpa(first, gpa) && region_owns_gpa(second, gpa),
{
    let page_size = SPEC_PAGE_SIZE;
    let first_base = first.vstart@.0;
    let second_base = second.vstart@.0;
    let first_page = first_base / page_size;
    let second_page = second_base / page_size;
    lemma_region_guest_page_linear(first, 0);
    lemma_region_guest_page_linear(second, 0);
    if first_base <= second_base {
        let i = (second_page - first_page) as nat;
        lemma_region_guest_page_linear(first, i);
        assert(region_owns_gpa(first, GuestPage(second_page)));
        assert(region_owns_gpa(second, GuestPage(second_page)));
    } else {
        let i = (first_page - second_page) as nat;
        lemma_region_guest_page_linear(second, i);
        assert(region_owns_gpa(first, GuestPage(first_page)));
        assert(region_owns_gpa(second, GuestPage(first_page)));
    }
}

/// Converts a shared guest page into concrete virtual-region overlap.
pub proof fn lemma_shared_gpa_implies_vmem_overlap(
    first: MemoryRegion,
    second: MemoryRegion,
    gpa: GuestPage,
)
    requires
        first.spec_valid(),
        second.spec_valid(),
        region_owns_gpa(first, gpa),
        region_owns_gpa(second, gpa),
    ensures
        first.spec_overlaps_vmem(second),
{
    let first_i = choose|i: nat| 0 <= i < first.pages && region_guest_page(first, i) == gpa;
    let second_i = choose|i: nat| 0 <= i < second.pages && region_guest_page(second, i) == gpa;
    lemma_region_guest_page_linear(first, first_i);
    lemma_region_guest_page_linear(second, second_i);
}

/// Produces a physical page shared by two physically overlapping valid regions.
pub proof fn lemma_pmem_overlap_implies_shared_page(first: MemoryRegion, second: MemoryRegion)
    requires
        first.spec_valid(),
        second.spec_valid(),
        first.spec_overlaps_pmem(second),
    ensures
        exists|page: PhysPage|
            region_pages(first).contains(page) && region_pages(second).contains(page),
{
    let page_size = SPEC_PAGE_SIZE;
    let first_base = first.pstart@.0;
    let second_base = second.pstart@.0;
    let first_page = first_base / page_size;
    let second_page = second_base / page_size;
    lemma_region_phys_page_linear(first, 0);
    lemma_region_phys_page_linear(second, 0);
    if first_base <= second_base {
        let i = (second_page - first_page) as nat;
        lemma_region_phys_page_linear(first, i);
        assert(region_pages(first).contains(PhysPage(second_page)));
        assert(region_pages(second).contains(PhysPage(second_page)));
    } else {
        let i = (first_page - second_page) as nat;
        lemma_region_phys_page_linear(second, i);
        assert(region_pages(first).contains(PhysPage(first_page)));
        assert(region_pages(second).contains(PhysPage(first_page)));
    }
}

/// Converts a shared physical page into concrete physical-region overlap.
pub proof fn lemma_shared_page_implies_pmem_overlap(
    first: MemoryRegion,
    second: MemoryRegion,
    page: PhysPage,
)
    requires
        first.spec_valid(),
        second.spec_valid(),
        region_pages(first).contains(page),
        region_pages(second).contains(page),
    ensures
        first.spec_overlaps_pmem(second),
{
    let first_i = choose|i: nat| 0 <= i < first.pages && region_phys_page(first, i) == page;
    let second_i = choose|i: nat| 0 <= i < second.pages && region_phys_page(second, i) == page;
    lemma_region_phys_page_linear(first, first_i);
    lemma_region_phys_page_linear(second, second_i);
}

/// Proves that abstraction preserves a concrete region's physical footprint.
pub proof fn lemma_region_to_abstract_pages(zid: nat, region: MemoryRegion)
    requires
        region.spec_valid(),
    ensures
        region_to_abstract(zid, region).pages() == region_pages(region),
{
    let abstract_region = region_to_abstract(zid, region);
    assert forall|page: PhysPage|
        abstract_region.pages().contains(page) <==> region_pages(region).contains(page) by {
        if abstract_region.pages().contains(page) {
            let i = (page.0 - region.pstart@.0 / SPEC_PAGE_SIZE) as nat;
            lemma_region_phys_page_linear(region, i);
        }
        if region_pages(region).contains(page) {
            let i = choose|i: nat| 0 <= i < region.pages && region_phys_page(region, i) == page;
            lemma_region_phys_page_linear(region, i);
        }
    }
    assert(abstract_region.pages() =~= region_pages(region));
}

/// Proves that abstraction preserves every stage-2 entry of a concrete region.
pub proof fn lemma_region_to_abstract_entries(zid: nat, region: MemoryRegion)
    requires
        region.spec_valid(),
    ensures
        region_to_abstract(zid, region).entries() == region_s2_entries(zid, region),
{
    let abstract_region = region_to_abstract(zid, region);
    let lhs = abstract_region.entries();
    let rhs = region_s2_entries(zid, region);
    assert forall|key: VmPageKey| lhs.contains_key(key) <==> rhs.contains_key(key) by {
        if lhs.contains_key(key) {
            let i = (key.gpa.0 - abstract_region.gpa_base) as nat;
            lemma_region_guest_page_linear(region, i);
        }
        if rhs.contains_key(key) {
            let i = choose|i: nat| 0 <= i < region.pages && region_guest_page(region, i) == key.gpa;
            lemma_region_guest_page_linear(region, i);
        }
    }
    assert forall|key: VmPageKey| #[trigger] lhs.contains_key(key) implies lhs[key] == rhs[key] by {
        let i = (key.gpa.0 - abstract_region.gpa_base) as nat;
        let j = choose|j: nat| 0 <= j < region.pages && region_guest_page(region, j) == key.gpa;
        lemma_region_guest_page_linear(region, i);
        lemma_region_guest_page_linear(region, j);
        lemma_region_phys_page_linear(region, i);
    }
    assert(lhs =~= rhs);
}

/// Every entry of `region` is installed with its exact value.
pub open spec fn abstract_region_installed(map: Map<VmPageKey, S2Entry>, region: Region) -> bool {
    forall|key: VmPageKey| #[trigger]
        region.entries().contains_key(key) ==> map.contains_key(key) && map[key]
            == region.entries()[key]
}

// ---------------------------------------------------------------------------
// Memory-set projections
// ---------------------------------------------------------------------------
/// Renders a concrete memory set as abstract stage-2 entries for one zone.
pub open spec fn memory_set_s2_entries(zid: nat, mem_set: SpecMemorySet) -> Map<
    VmPageKey,
    S2Entry,
> {
    Map::new(
        |key: VmPageKey|
            key.vm == VmId(zid) && mem_set.mappings.contains_key(vaddr_of_gpa(key.gpa)),
        |key: VmPageKey| frame_to_s2(mem_set.mappings[vaddr_of_gpa(key.gpa)]),
    )
}

/// Physical pages targeted by a concrete memory set.
pub open spec fn memory_set_mapped_pages(mem_set: SpecMemorySet) -> Set<PhysPage> {
    Set::new(
        |page: PhysPage|
            exists|vaddr: SpecVAddr| #[trigger]
                mem_set.mappings.contains_key(vaddr) && frame_phys_page(mem_set.mappings[vaddr])
                    == page,
    )
}

// ---------------------------------------------------------------------------
// Memory-set entry facts
// ---------------------------------------------------------------------------

/// Shows that an installed concrete region contributes all of its abstract entries.
pub proof fn lemma_region_in_memory_set_maps_entries(
    zid: nat,
    mem_set: SpecMemorySet,
    region: MemoryRegion,
)
    requires
        mem_set.wf(),
        mem_set.regions.contains(region),
    ensures
        abstract_region_installed(
            memory_set_s2_entries(zid, mem_set),
            region_to_abstract(zid, region),
        ),
{
    lemma_region_to_abstract_entries(zid, region);
}

/// Relates concrete memory-set insertion to abstract stage-2 map insertion.
pub proof fn lemma_memory_set_s2_insert(zid: nat, mem_set: SpecMemorySet, region: MemoryRegion)
    requires
        mem_set.wf(),
        region.spec_valid(),
        !mem_set.overlaps_vmem(region),
    ensures
        memory_set_s2_entries(zid, mem_set.insert_region(region)) =~= memory_set_s2_entries(
            zid,
            mem_set,
        ).union_prefer_right(region_s2_entries(zid, region)),
{
    let old = memory_set_s2_entries(zid, mem_set);
    let added = region_s2_entries(zid, region);
    let new = memory_set_s2_entries(zid, mem_set.insert_region(region));
    assert forall|key: VmPageKey| #[trigger]
        new.contains_key(key) <==> old.union_prefer_right(added).contains_key(key) by {
        lemma_region_gpa_mapped_iff(region, key.gpa);
    }
    assert forall|key: VmPageKey|
        #![trigger new[key]]
        #![trigger old.union_prefer_right(added)[key]]
        new.contains_key(key) implies new[key] == old.union_prefer_right(added)[key] by {
        lemma_region_gpa_mapped_iff(region, key.gpa);
        if region.spec_mappings().contains_key(vaddr_of_gpa(key.gpa)) {
            lemma_region_s2_value(zid, region, key);
        }
    }
}

/// Relates concrete memory-set removal to abstract stage-2 map removal.
pub proof fn lemma_memory_set_s2_remove(zid: nat, mem_set: SpecMemorySet, region: MemoryRegion)
    requires
        mem_set.wf(),
        mem_set.regions.contains(region),
    ensures
        memory_set_s2_entries(zid, mem_set.remove_region_exact(region)) =~= memory_set_s2_entries(
            zid,
            mem_set,
        ).remove_keys(region_s2_entries(zid, region).dom()),
{
    let old = memory_set_s2_entries(zid, mem_set);
    let removed = region_s2_entries(zid, region);
    let new = memory_set_s2_entries(zid, mem_set.remove_region_exact(region));
    assert forall|key: VmPageKey| #[trigger]
        new.contains_key(key) <==> old.remove_keys(removed.dom()).contains_key(key) by {
        lemma_region_gpa_mapped_iff(region, key.gpa);
    }
    assert(forall|key: VmPageKey|
        #![trigger new[key]]
        #![trigger old.remove_keys(removed.dom())[key]]
        new.contains_key(key) ==> new[key] == old.remove_keys(removed.dom())[key]);
}

/// Virtual disjointness makes every entry of a new region fresh in a concrete
/// memory set's abstract map.
pub proof fn lemma_memory_set_s2_entries_fresh(
    zid: nat,
    mem_set: SpecMemorySet,
    region: MemoryRegion,
)
    requires
        mem_set.wf(),
        region.spec_valid(),
        !mem_set.overlaps_vmem(region),
    ensures
        forall|key: VmPageKey| #[trigger]
            region_s2_entries(zid, region).contains_key(key)
                ==> !memory_set_s2_entries(zid, mem_set).contains_key(key),
{
    assert forall|key: VmPageKey| #[trigger]
        region_s2_entries(zid, region).contains_key(
            key,
        ) implies !memory_set_s2_entries(zid, mem_set).contains_key(key) by {
        if memory_set_s2_entries(zid, mem_set).contains_key(key) {
            let vaddr = vaddr_of_gpa(key.gpa);
            let frame = mem_set.mappings[vaddr];
            assert(mem_set.mappings.contains_pair(vaddr, frame));
            let (old, i) = choose|old: MemoryRegion, i: nat|
                mem_set.regions.contains(old) && 0 <= i < old.pages
                    && vaddr == old.spec_page_vaddr(i) && frame == old.spec_frame(i);
            lemma_gpa_vaddr_roundtrip(old, i);
            assert(region_owns_gpa(old, key.gpa)) by {
                let witness = i;
                lemma_vaddr_of_gpa_injective(region_guest_page(old, i), key.gpa);
            }
            assert(region_owns_gpa(region, key.gpa));
            lemma_shared_gpa_implies_vmem_overlap(old, region, key.gpa);
        }
    }
}

// ---------------------------------------------------------------------------
// Memory-set physical-page facts
// ---------------------------------------------------------------------------

/// Finds an installed region whose footprint contains a mapped physical page.
pub proof fn lemma_memory_set_mapped_page_has_region(mem_set: SpecMemorySet, page: PhysPage)
    requires
        mem_set.wf(),
        memory_set_mapped_pages(mem_set).contains(page),
    ensures
        exists|region: MemoryRegion| #[trigger]
            mem_set.regions.contains(region) && region_pages(region).contains(page),
{
    let vaddr = choose|vaddr: SpecVAddr| #[trigger]
        mem_set.mappings.contains_key(vaddr) && frame_phys_page(mem_set.mappings[vaddr]) == page;
    let frame = mem_set.mappings[vaddr];
    assert(mem_set.mappings.contains_pair(vaddr, frame));
    assert(exists|region: MemoryRegion, i: nat|
        #![trigger mem_set.regions.contains(region), region.spec_page_vaddr(i)]
        mem_set.regions.contains(region) && 0 <= i < region.pages && vaddr
            == region.spec_page_vaddr(i) && frame == region.spec_frame(i));
    let (region, i) = choose|region: MemoryRegion, i: nat|
        mem_set.regions.contains(region) && 0 <= i < region.pages && vaddr
            == region.spec_page_vaddr(i) && frame == region.spec_frame(i);
    lemma_region_phys_page_linear(region, i);
    assert(region_phys_page(region, i) == page);
    assert(region_pages(region).contains(page));
}

/// Every physical page of an installed region is represented by a mapping in
/// the containing memory set.
pub proof fn lemma_memory_set_region_page_is_mapped(
    mem_set: SpecMemorySet,
    region: MemoryRegion,
    page: PhysPage,
)
    requires
        mem_set.wf(),
        mem_set.regions.contains(region),
        region_pages(region).contains(page),
    ensures
        memory_set_mapped_pages(mem_set).contains(page),
{
    let i = choose|i: nat| 0 <= i < region.pages && region_phys_page(region, i) == page;
    let vaddr = region.spec_page_vaddr(i);
    lemma_region_phys_page_linear(region, i);
    assert(mem_set.mappings.contains_pair(vaddr, region.spec_frame(i)));
    assert(frame_phys_page(mem_set.mappings[vaddr]) == page);
}

/// A well-formed memory set maps exactly the union of its stored regions'
/// physical footprints.
pub proof fn lemma_memory_set_mapped_pages_iff_region_page(mem_set: SpecMemorySet, page: PhysPage)
    requires
        mem_set.wf(),
    ensures
        memory_set_mapped_pages(mem_set).contains(page) <==> exists|region: MemoryRegion|
         #[trigger]
            mem_set.regions.contains(region) && region_pages(region).contains(page),
{
    if memory_set_mapped_pages(mem_set).contains(page) {
        lemma_memory_set_mapped_page_has_region(mem_set, page);
    }
    if exists|region: MemoryRegion| #[trigger]
        mem_set.regions.contains(region) && region_pages(region).contains(page) {
        let region = choose|region: MemoryRegion| #[trigger]
            mem_set.regions.contains(region) && region_pages(region).contains(page);
        lemma_memory_set_region_page_is_mapped(mem_set, region, page);
    }
}

/// Inserting a virtually fresh region adds exactly its physical footprint to
/// the set of mapped physical pages. Existing physical aliases are harmless
/// because the projection is a set.
pub proof fn lemma_memory_set_mapped_pages_insert(mem_set: SpecMemorySet, region: MemoryRegion)
    requires
        mem_set.wf(),
        region.spec_valid(),
        !mem_set.regions.contains(region),
        !mem_set.overlaps_vmem(region),
    ensures
        memory_set_mapped_pages(mem_set.insert_region(region)) =~= memory_set_mapped_pages(
            mem_set,
        ).union(region_pages(region)),
{
    mem_set.lemma_insert_region_wf(region);
    assert forall|page: PhysPage| #[trigger]
        memory_set_mapped_pages(mem_set.insert_region(region)).contains(page)
            <==> memory_set_mapped_pages(mem_set).union(region_pages(region)).contains(page) by {
        lemma_memory_set_mapped_pages_iff_region_page(mem_set.insert_region(region), page);
        lemma_memory_set_mapped_pages_iff_region_page(mem_set, page);
        if memory_set_mapped_pages(mem_set.insert_region(region)).contains(page) {
            let stored = choose|stored: MemoryRegion| #[trigger]
                mem_set.insert_region(region).regions.contains(stored) && region_pages(
                    stored,
                ).contains(page);
            if stored != region {
                assert(mem_set.regions.contains(stored));
                lemma_memory_set_region_page_is_mapped(mem_set, stored, page);
            }
        }
        if region_pages(region).contains(page) {
            lemma_memory_set_region_page_is_mapped(mem_set.insert_region(region), region, page);
        }
        if memory_set_mapped_pages(mem_set).contains(page) {
            let stored = choose|stored: MemoryRegion| #[trigger]
                mem_set.regions.contains(stored) && region_pages(stored).contains(page);
            lemma_memory_set_region_page_is_mapped(mem_set.insert_region(region), stored, page);
        }
    }
}

/// Removing a region that is physically disjoint from every other stored
/// region removes exactly its physical footprint from the mapped-page set.
pub proof fn lemma_memory_set_mapped_pages_remove_disjoint(
    mem_set: SpecMemorySet,
    region: MemoryRegion,
)
    requires
        mem_set.wf(),
        mem_set.regions.contains(region),
        forall|other: MemoryRegion| #[trigger]
            mem_set.regions.contains(other) && other != region ==> !other.spec_overlaps_pmem(
                region,
            ),
    ensures
        memory_set_mapped_pages(mem_set.remove_region_exact(region)) =~= memory_set_mapped_pages(
            mem_set,
        ).difference(region_pages(region)),
{
    mem_set.lemma_remove_region_exact_wf(region);
    assert forall|page: PhysPage| #[trigger]
        memory_set_mapped_pages(mem_set.remove_region_exact(region)).contains(page)
            <==> memory_set_mapped_pages(mem_set).difference(region_pages(region)).contains(
            page,
        ) by {
        lemma_memory_set_mapped_pages_iff_region_page(mem_set.remove_region_exact(region), page);
        lemma_memory_set_mapped_pages_iff_region_page(mem_set, page);
        if memory_set_mapped_pages(mem_set.remove_region_exact(region)).contains(page) {
            let stored = choose|stored: MemoryRegion| #[trigger]
                mem_set.remove_region_exact(region).regions.contains(stored) && region_pages(
                    stored,
                ).contains(page);
            assert(stored != region);
            if region_pages(region).contains(page) {
                lemma_shared_page_implies_pmem_overlap(stored, region, page);
            }
        }
        if memory_set_mapped_pages(mem_set).contains(page) && !region_pages(region).contains(page) {
            let stored = choose|stored: MemoryRegion| #[trigger]
                mem_set.regions.contains(stored) && region_pages(stored).contains(page);
            assert(stored != region);
            lemma_memory_set_region_page_is_mapped(
                mem_set.remove_region_exact(region),
                stored,
                page,
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Zone and flattened-map projections
// ---------------------------------------------------------------------------
/// Physical pages targeted by the zone's current CPU mappings.
pub open spec fn zone_cpu_mapped_pages(zone: GhostZone) -> Set<PhysPage> {
    memory_set_mapped_pages(zone.cpu_mem_set)
}

/// Physical pages targeted by the zone's current IOMMU mappings.
pub open spec fn zone_iommu_mapped_pages(zone: GhostZone) -> Set<PhysPage> {
    memory_set_mapped_pages(zone.iommu_mem_set)
}

/// Abstract CPU stage-2 entries installed for one zone.
pub open spec fn zone_s2_entries(zid: nat, zone: GhostZone) -> Map<VmPageKey, S2Entry> {
    memory_set_s2_entries(zid, zone.cpu_mem_set)
}

/// Abstract IOMMU stage-2 entries installed for one zone.
pub open spec fn zone_iommu_s2_entries(zid: nat, zone: GhostZone) -> Map<VmPageKey, S2Entry> {
    memory_set_s2_entries(zid, zone.iommu_mem_set)
}

/// Combines every live zone's CPU entries into one policy-neutral S2 map.
pub open spec fn zones_s2_map(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
) -> Map<VmPageKey, S2Entry> {
    Map::new(
        |key: VmPageKey|
            zone_ids.contains(key.vm.0)
                && zone_s2_entries(key.vm.0, zones[key.vm.0]).contains_key(key),
        |key: VmPageKey| zone_s2_entries(key.vm.0, zones[key.vm.0])[key],
    )
}

/// Combines every live zone's IOMMU entries into one policy-neutral S2 map.
pub open spec fn zones_iommu_s2_map(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
) -> Map<VmPageKey, S2Entry> {
    Map::new(
        |key: VmPageKey|
            zone_ids.contains(key.vm.0)
                && zone_iommu_s2_entries(key.vm.0, zones[key.vm.0]).contains_key(key),
        |key: VmPageKey| zone_iommu_s2_entries(key.vm.0, zones[key.vm.0])[key],
    )
}

// ---------------------------------------------------------------------------
// Flattened-map update facts
// ---------------------------------------------------------------------------

/// Lifts one zone-local CPU insertion into the flattened S2 map.
pub proof fn lemma_zones_s2_insert(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
    zid: nat,
    region: MemoryRegion,
)
    requires
        zone_ids.contains(zid),
        zones.contains_key(zid),
        zones[zid].wf(),
        region.spec_valid(),
        !zones[zid].cpu_mem_set.overlaps_vmem(region),
    ensures
        zones_s2_map(zone_ids, zones.insert(zid, zones[zid].cpu_insert_region(region)))
            =~= zones_s2_map(zone_ids, zones).union_prefer_right(
                region_s2_entries(zid, region),
            ),
{
    lemma_memory_set_s2_insert(zid, zones[zid].cpu_mem_set, region);
    let lhs = zones_s2_map(zone_ids, zones.insert(zid, zones[zid].cpu_insert_region(region)));
    let rhs = zones_s2_map(zone_ids, zones).union_prefer_right(region_s2_entries(zid, region));
    assert(forall|key: VmPageKey| #[trigger] lhs.contains_key(key) <==> rhs.contains_key(key));
    assert(forall|key: VmPageKey|
        #![trigger lhs[key]]
        #![trigger rhs[key]]
        lhs.contains_key(key) ==> lhs[key] == rhs[key]);
}

/// Lifts one zone-local CPU removal into the flattened S2 map.
pub proof fn lemma_zones_s2_remove(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
    zid: nat,
    region: MemoryRegion,
)
    requires
        zone_ids.contains(zid),
        zones.contains_key(zid),
        zones[zid].wf(),
        zones[zid].cpu_mem_set.regions.contains(region),
    ensures
        zones_s2_map(zone_ids, zones.insert(zid, zones[zid].cpu_remove_region(region)))
            =~= zones_s2_map(zone_ids, zones).remove_keys(region_s2_entries(zid, region).dom()),
{
    lemma_memory_set_s2_remove(zid, zones[zid].cpu_mem_set, region);
    let lhs = zones_s2_map(zone_ids, zones.insert(zid, zones[zid].cpu_remove_region(region)));
    let rhs = zones_s2_map(zone_ids, zones).remove_keys(region_s2_entries(zid, region).dom());
    assert(forall|key: VmPageKey| #[trigger] lhs.contains_key(key) <==> rhs.contains_key(key));
    assert(forall|key: VmPageKey|
        #![trigger lhs[key]]
        #![trigger rhs[key]]
        lhs.contains_key(key) ==> lhs[key] == rhs[key]);
}

/// Lifts one zone-local IOMMU insertion into the flattened IOMMU map.
pub proof fn lemma_zones_iommu_s2_insert(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
    zid: nat,
    region: MemoryRegion,
)
    requires
        zone_ids.contains(zid),
        zones.contains_key(zid),
        zones[zid].wf(),
        region.spec_valid(),
        !zones[zid].iommu_mem_set.overlaps_vmem(region),
    ensures
        zones_iommu_s2_map(zone_ids, zones.insert(zid, zones[zid].iommu_insert_region(region)))
            =~= zones_iommu_s2_map(zone_ids, zones).union_prefer_right(
                region_s2_entries(zid, region),
            ),
{
    lemma_memory_set_s2_insert(zid, zones[zid].iommu_mem_set, region);
    let lhs = zones_iommu_s2_map(
        zone_ids,
        zones.insert(zid, zones[zid].iommu_insert_region(region)),
    );
    let rhs =
        zones_iommu_s2_map(zone_ids, zones).union_prefer_right(region_s2_entries(zid, region));
    assert(forall|key: VmPageKey| #[trigger] lhs.contains_key(key) <==> rhs.contains_key(key));
    assert(forall|key: VmPageKey|
        #![trigger lhs[key]]
        #![trigger rhs[key]]
        lhs.contains_key(key) ==> lhs[key] == rhs[key]);
}

/// Lifts one zone-local IOMMU removal into the flattened IOMMU map.
pub proof fn lemma_zones_iommu_s2_remove(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
    zid: nat,
    region: MemoryRegion,
)
    requires
        zone_ids.contains(zid),
        zones.contains_key(zid),
        zones[zid].wf(),
        zones[zid].iommu_mem_set.regions.contains(region),
    ensures
        zones_iommu_s2_map(zone_ids, zones.insert(zid, zones[zid].iommu_remove_region(region)))
            =~= zones_iommu_s2_map(zone_ids, zones).remove_keys(
                region_s2_entries(zid, region).dom(),
            ),
{
    lemma_memory_set_s2_remove(zid, zones[zid].iommu_mem_set, region);
    let lhs = zones_iommu_s2_map(
        zone_ids,
        zones.insert(zid, zones[zid].iommu_remove_region(region)),
    );
    let rhs =
        zones_iommu_s2_map(zone_ids, zones).remove_keys(region_s2_entries(zid, region).dom());
    assert(forall|key: VmPageKey| #[trigger] lhs.contains_key(key) <==> rhs.contains_key(key));
    assert(forall|key: VmPageKey|
        #![trigger lhs[key]]
        #![trigger rhs[key]]
        lhs.contains_key(key) ==> lhs[key] == rhs[key]);
}

// ---------------------------------------------------------------------------
// Flattened-map freshness facts
// ---------------------------------------------------------------------------

/// A CPU region that is fresh in its zone is fresh in the flattened S2 map.
pub proof fn lemma_zones_s2_entries_fresh(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
    zid: nat,
    region: MemoryRegion,
)
    requires
        zone_ids.contains(zid),
        zones.contains_key(zid),
        zones[zid].wf(),
        region.spec_valid(),
        !zones[zid].cpu_mem_set.overlaps_vmem(region),
    ensures
        forall|key: VmPageKey| #[trigger]
            region_s2_entries(zid, region).contains_key(key)
                ==> !zones_s2_map(zone_ids, zones).contains_key(key),
{
    lemma_memory_set_s2_entries_fresh(zid, zones[zid].cpu_mem_set, region);
    assert forall|key: VmPageKey| #[trigger]
        region_s2_entries(zid, region).contains_key(
            key,
        ) implies !zones_s2_map(zone_ids, zones).contains_key(key) by {
        if zones_s2_map(zone_ids, zones).contains_key(key) {
            assert(key.vm == VmId(zid));
            assert(memory_set_s2_entries(zid, zones[zid].cpu_mem_set).contains_key(key));
        }
    }
}

/// An IOMMU region that is fresh in its zone is fresh in the flattened map.
pub proof fn lemma_zones_iommu_s2_entries_fresh(
    zone_ids: Set<nat>,
    zones: Map<nat, GhostZone>,
    zid: nat,
    region: MemoryRegion,
)
    requires
        zone_ids.contains(zid),
        zones.contains_key(zid),
        zones[zid].wf(),
        region.spec_valid(),
        !zones[zid].iommu_mem_set.overlaps_vmem(region),
    ensures
        forall|key: VmPageKey| #[trigger]
            region_s2_entries(zid, region).contains_key(key)
                ==> !zones_iommu_s2_map(zone_ids, zones).contains_key(key),
{
    lemma_memory_set_s2_entries_fresh(zid, zones[zid].iommu_mem_set, region);
    assert forall|key: VmPageKey| #[trigger]
        region_s2_entries(zid, region).contains_key(
            key,
        ) implies !zones_iommu_s2_map(zone_ids, zones).contains_key(key) by {
        if zones_iommu_s2_map(zone_ids, zones).contains_key(key) {
            assert(key.vm == VmId(zid));
            assert(memory_set_s2_entries(zid, zones[zid].iommu_mem_set).contains_key(key));
        }
    }
}

} // verus!
